FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel

RUN python -m pip install pip==21.2.4 \
    && pip install -U --no-cache-dir \
        tensorflow==2.9.1 \
        tqdm==4.64.0 \
        torchinfo==1.7.0
